version: 2

run:
  timeout: 5m
  tests: true

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/substantialcattle5/sietch

linters:
  enable:
    # Core linters - essential for code quality
    - govet
    - staticcheck
    - unused
    - ineffassign
    
    # Basic code quality
    - misspell
  disable:
    # Disable noisy linters for minimal CI
    - errcheck

formatters:
  enable:
    - gofmt
    - goimports

issues:
  exclude-dirs:
    - vendor
    - test_vaults
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"
  exclude-rules:
    # Be more lenient with test files
    - path: _test\.go
      linters:
        - staticcheck
    # Exclude generated files from formatting rules
    - path: \.pb\.go
      linters:
        - gofmt
        - goimports