run:
  timeout: 5m
  tests: true

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/substantialcattle5/sietch
  govet:
    disable:
      - shadow
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  gocritic:
    enabled-tags:
      - performance
      - style
    disabled-checks:
      - wrapperFunc
  gosec:
    excludes:
      - G404
      - G304
      - G301
      - G302
      - G306
      - G104

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - misspell
    - lll
    - unparam
    - nakedret
    - prealloc
    - gocritic
    - gocyclo
    - dupl
    - goconst
    - gosec
    - unconvert
    - gofumpt
    - whitespace
    - gci
    - nolintlint
    - exportloopref
    - sqlclosecheck
    - bodyclose
    - noctx
    - rowserrcheck

issues:
  exclude-dirs:
    - vendor
    - test_vaults
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - lll
        - unparam
        - goconst
    - path: internal/p2p/
      linters:
        - gosec
    - text: "shadow: declaration of \"err\""
      linters:
        - govet
    - path: \.pb\.go
      linters:
        - gofmt
        - goimports
    - source: "^//go:generate "
      linters:
        - lll
  max-issues-per-linter: 0
  max-same-issues: 0