run:
  timeout: 5m
  tests: true

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/substantialcattle5/sietch
  govet:
    disable:
      - shadow
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  gocritic:
    enabled-tags:
      - performance
      - style
    disabled-checks:
      - wrapperFunc
  gosec:
    excludes:
      - G404
      - G304
      - G301
      - G302
      - G306
      - G104

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - misspell
    - lll
    - unparam
    - nakedret
    - prealloc
    - gocritic
    - gocyclo
    - dupl
    - goconst
    - gosec
    - unconvert
    - gofumpt
    - whitespace
    - gci
    - nolintlint
    - copyloopvar
    - sqlclosecheck
    - bodyclose
    - noctx
    - rowserrcheck

issues:
  exclude-dirs:
    - vendor
    - test_vaults
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - lll
        - unparam
        - goconst
        - gocritic
    - path: internal/p2p/
      linters:
        - gosec
        - gocyclo
        - gocritic
    - text: "shadow: declaration of \"err\""
      linters:
        - govet
    - path: \.pb\.go
      linters:
        - gofmt
        - goimports
    - source: "^//go:generate "
      linters:
        - lll
    # Temporarily exclude some noisy rules during development
    - text: "octalLiteral"
      linters:
        - gocritic
    - text: "paramTypeCombine"
      linters:
        - gocritic
    - text: "hugeParam"
      linters:
        - gocritic
    - text: "appendAssign"
      linters:
        - gocritic
    - text: "rangeValCopy"
      linters:
        - gocritic
    - text: "ifElseChain"
      linters:
        - gocritic
    - text: "commentFormatting"
      linters:
        - gocritic
    - text: "emptyStringTest"
      linters:
        - gocritic
    - text: "has .* occurrences, make it a constant"
      linters:
        - goconst
    - text: "cyclomatic complexity .* is high"
      linters:
        - gocyclo
    - text: "unnecessary conversion"
      linters:
        - unconvert
    - text: "func .* is unused"
      linters:
        - unused
    - text: "empty branch"
      linters:
        - staticcheck
    - text: "possible nil pointer dereference"
      linters:
        - staticcheck
    - text: "The line is .* characters long"
      linters:
        - lll
    - text: "File is not properly formatted"
      linters:
        - gci
        - gofumpt
        - goimports
    - text: "unnamedResult"
      linters:
        - gocritic
  max-issues-per-linter: 10
  max-same-issues: 3